window.PMX_CONFIG = Object.freeze({
  gameId: "PMX-WS-2026-W01",
  gameLabel: "SEASON OPENER",
  kickerMobile: "SEASON OPENER",
  kickerDesktop: "SEASON OPENER",
  week: "WEEK 1",
  opponent: "VIKINGS",
  opponentLong: "Minnesota Vikings",
  homeAway: "AWAY",
  date: "DOM 13 SEP",
  time: "14:25",
  timezone: "America/Mexico_City",
  venue: "Wingstop Condesa",
  venueWording: "Casa Oficial de Packers en CDMX",
  registrationUrl: "https://share.forms.app/form/6a96032ee64cd5f15d1688aa",
  mapsUrl: "https://www.google.com/maps/search/?api=1&query=Wingstop%20Condesa&query_place_id=ChIJ8WFFePj_0YURO5krqxenfu8",
  heroImageUrl: "",
  dataPending: true,
  promoEnabled: false,
  promoTitle: "",
  promoDescription: "",
  promoUrl: "",
  specialEnabled: false,
  specialTitle: "",
  specialDescription: "",
  calendarUrl: "https://packersmexico.github.io/calendario/",
  gopackgoUrl: "https://www.youtube.com/@gopackgomx6092",
  analytics: Object.freeze({
    GA4_MEASUREMENT_ID: "G-QEN5F5YY14",
    hubVersion: "p0",
    eventVersion: "1.0"
  }),
  socialUrls: Object.freeze({
    facebook: "https://www.facebook.com/gopackgomx/",
    instagram: "https://www.instagram.com/packers_mx/",
    x: "https://x.com/Packers_Mx",
    tiktok: "https://www.tiktok.com/@packers_mx",
    youtube: "https://www.youtube.com/@gopackgomx6092"
  })
});
